---
name: Tie-DxHash
version: v1.0.0
author:
  - 'Kevin Ruscoe <kevin@sapphireoflondon.org>'
abstract: keeps insertion order; allows duplicate keys
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  Tie::DxHash:
    file: lib/Tie/DxHash.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 1
        - 0
        - 0
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
